---
name: Build Template

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{matrix.system}}
    strategy:
      matrix:
        system:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        node-version:
          - 18

    env:
      PYTHON_VERSION: 3.11

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: node${{matrix.node-version}} setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: python3.11 setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: install-mk
        run: |
          pip3.11 install vmklib

      - name: test
        run: |
          mk test yaml
