---
name: Build Template

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{matrix.system}}
    strategy:
      matrix:
        system:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        node_version:
          - 18

    env:
      PYTHON_VERSION: 3.9

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: node${{matrix.node_version}} setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node_version}}

      - name: python3.9 setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install-mk
        run: |
          pip3.9 install vmklib

      - name: test
        run: |
          mk test yaml
